// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX8qVUeN-Tj2pyoLCQoN6UmE5HXnzfpqQ',
    appId: '1:880234431543:web:1e749d4e867ad0004a2bb2',
    messagingSenderId: '880234431543',
    projectId: 'todo-app-953cc',
    authDomain: 'todo-app-953cc.firebaseapp.com',
    storageBucket: 'todo-app-953cc.appspot.com',
    measurementId: 'G-6RQVYM2BJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM-uN4WS9NiNMPNc_N4-63joX_bndn4bg',
    appId: '1:880234431543:android:a19eabc04846f44e4a2bb2',
    messagingSenderId: '880234431543',
    projectId: 'todo-app-953cc',
    storageBucket: 'todo-app-953cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHJBal1sM3Oq2dhmVEucPO5MBCGaYouxc',
    appId: '1:880234431543:ios:ce25de86e4f0818c4a2bb2',
    messagingSenderId: '880234431543',
    projectId: 'todo-app-953cc',
    storageBucket: 'todo-app-953cc.appspot.com',
    iosClientId: '880234431543-s7b2v760pk3k1uu15vgvcc1sioq68085.apps.googleusercontent.com',
    iosBundleId: 'y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHJBal1sM3Oq2dhmVEucPO5MBCGaYouxc',
    appId: '1:880234431543:ios:80b0dd00d466a42a4a2bb2',
    messagingSenderId: '880234431543',
    projectId: 'todo-app-953cc',
    storageBucket: 'todo-app-953cc.appspot.com',
    iosClientId: '880234431543-pssr36hh8sm1e9933946671c2uupqhqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
